Blog_app/urls.py
from django.urls import path
from .import views
from django.urls import reverse

app_name = 'Blog_app'

urlpatterns = [
    # path('', views.home_blog, name='home_blog'),
    path('', views.all_blog, name='all_blog'),
    path('<slug:blog>/', views.blog, name='blog'),
    path('all/categories/', views.all_blog_category, name='all_blog_category'),

    path('category/<slug:slug_of_category>/',
         views.blog_category, name='blog_category'),

    path('about/us/', views.about, name='about'),
    path('search/blog/', views.search_blog, name='search_blog'),
]

New_Blog_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('carousel/', include('Carousel_app.urls', namespace='Carousel_app')),
    path('', include('Blog_app.urls', namespace='Blog_app')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% comment %} <!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- favicon -->
    <link rel="icon" sizes="16x16" href="{% static 'blog/assets/img/favicon.png' %} ">

    <!-- Title -->
    <title> NoonPost. - Personal Blog HTML Template </title>

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- CSS Plugins -->
    <link rel="stylesheet" href="{% static 'blog/assets/css/all.css'%}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/elegant-font-icons.css'%}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/owl.carousel.css'%}">

    <!-- main style -->
    <link rel="stylesheet" href="{% static 'blog/assets/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/custom.css'%}">
  </head>
  <body>

  {% include "header.html" %}
  {% block mainblock %}
  
  {% endblock mainblock %}
  <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html> {% endcomment %}

{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- favicon 
    <link rel="icon" sizes="16x16" href="{% static 'blog/assets/img/favicon.png' %} ">
  -->
    <!-- Title -->
    
    
      
    <title>
    {% block titleblock %}
      
    {% endblock titleblock %}
    </title>

    <!-- Font Google -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- CSS Plugins -->
    <link rel="stylesheet" href="{% static 'blog/assets/css/all.css'%}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/elegant-font-icons.css'%}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/owl.carousel.css'%}">

    <!-- main style -->
    <link rel="stylesheet" href="{% static 'blog/assets/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'blog/assets/css/custom.css'%}">
</head>

<body>
    <!--loading -->
    <div class="loading">
        <div class="circle"></div>
    </div>
    <!--/-->

    <!-- Navigation-->
    {% include "header.html" %}

    <!--/-->
  {% block mainblock %}
    <!--masonry-layout-->

    <!--/-->

    <!--footer-->


    <!--Search-form-->

    <!--/-->
  {% endblock mainblock %}


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'blog/assets/js/jquery-3.5.0.min.js'%}"></script>
    <script src="{% static 'blog/assets/js/popper.min.js'%}"></script>
    <script src="{% static 'blog/assets/js/bootstrap.min.js'%}"></script>

    <!-- JS Plugins  -->
    <script src="{% static 'blog/assets/js/ajax-contact.js'%}"></script>
    <script src="{% static 'blog/assets/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'blog/assets/js/switch.js'%}"></script>
    
    <!-- JS main  -->
    <script src="{% static 'blog/assets/js/main.js'%}"></script>


</body>

</html>

templates/footer.html
{% load static %}
<footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright">
                        <p>© Copyright 2021  <a href="#">Rakib-Digonto</a> , All rights reserved.</p>
                    </div>
                    <div class="back">
                        <a href="#" class="back-top">
                            <i class="arrow_up"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <!--logo-->
            <div class="logo">
                <a href="index.html">
                    <img src="{% static 'blog/assets/img/logo-dark.png' %}"alt="" class="logo-dark">
                    <img src="{% static 'blog/assets/img/logo-dark.png' %}" alt="" class="logo-white">
                </a>
            </div><!--/-->
        
            <!--navbar-collapse-->
            <div class="collapse navbar-collapse" id="main_nav">
                <ul class="navbar-nav ml-auto mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/"> Home </a>
                    </li>

                    {% comment %} <li class="nav-item dropdown">
                        <a class="nav-link  dropdown-toggle" href="post-default.html" data-toggle="dropdown"> Posts Features </a>
                        <ul class="dropdown-menu fade-up">
                            <li><a class="dropdown-item" href="post-default.html"> post default</a></li>
                            <li>
                                <a class="dropdown-item" href="post-video.html"> post video</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="post-audio.html"> post audio</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="post-gallery.html"> post gallery</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="post-no-sidebar.html"> post no sidebar </a>
                            </li>
                            <li><a class="dropdown-item" href="post-left-sidebar.html"> post left sidebar </a></li>
                        </ul>
                    </li> {% endcomment %}
                   
                    {% comment %} <li class="nav-item dropdown">
                        <a class="nav-link  dropdown-toggle" href="{% url 'Blog_app:all_blog_category' %}" data-toggle="dropdown"> All Category </a>
                        <ul class="dropdown-menu fade-up">
                            <li>
                                <a class="dropdown-item" href="{% url 'Blog_app:about' %}"> About </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="author.html"> author </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="login.html"> Login </a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="register.html"> Sign up </a>
                            </li>
                            <li>
                                <a class="dropdown-item " href="page404.html"> Page 404 </a>
                            </li>
                        </ul>
                    </li> {% endcomment %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Blog_app:all_blog' %}"> All Blogs </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Blog_app:all_blog_category' %}"> All Category </a>
                    </li>
                    
                </ul>
            </div><!--/-->
            
            <!--navbar-right-->
            <div class="navbar-right ml-auto">
                <div class="theme-switch-wrapper">
                    <label class="theme-switch" for="checkbox">
                        <input type="checkbox" id="checkbox" />
                        <div class="slider round"></div>
                    </label>
                </div>

                <div class="social-icones">
                    <ul class="list-inline">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                    </ul>
                </div>
               
                <div class="search-icon">
                    <i class="icon_search"></i>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </nav>