Blog_app/urls.py
from django.urls import path
from .import views
from django.urls import reverse

app_name = 'Blog_app'

urlpatterns = [
    # path('', views.home_blog, name='home_blog'),
    path('', views.all_blog, name='all_blog'),
    path('<slug:blog>/', views.blog, name='blog'),
    path('all/categories/', views.all_blog_category, name='all_blog_category'),

    path('category/<slug:slug_of_category>/',
         views.blog_category, name='blog_category'),

    path('about/us/', views.about, name='about'),
    path('search/blog/', views.search_blog, name='search_blog'),
]

New_Blog_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('carousel/', include('Carousel_app.urls', namespace='Carousel_app')),
    path('', include('Blog_app.urls', namespace='Blog_app')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/blog_temp/about.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
      Read Blog
{% endblock titleblock %}
{% block mainblock %}

<body> 
    <!--loading -->
    <div class="loading">
        <div class="circle"></div>
    </div>
    <!--/-->

    <!-- Navigation-->
    {% include "header.html" %}
    <!--/-->
    
    <!--category-->
    <section class="categorie-section">
        <div class="container-fluid">
            <div class="row">
            </div>
        </div>
    </section>

    <!--blog-grid-->
        <section class="blog-grid">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 mt-30">
                        <div>
                        <h3>About Us</h3>
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo doloribus cupiditate voluptate sapiente consequatur saepe accusantium, similique laborum ipsam officiis?
                        
                        </div>
                        
                    </div>

                    </div>
                </div>
            </div>
        </div>
    </section><!--/-->

    
    <!--footer-->
    {% include "footer.html" %}

    <!--Search-form-->
    <div class="search">
        <div class="container-fluid">
            <div class="search-width  text-center">
                <button type="button" class="close">
                    <i class="icon_close"></i>
                </button>
                <form class="search-form" action="#">
                    <input type="search" value="" placeholder="What are you looking for?">
                    <button type="submit" class="search-btn">search</button>
                </form>
            </div>
        </div>
    </div>
    <!--/-->

  {% endblock mainblock %}

templates/blog_temp/all_category.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
      Read Blog
{% endblock titleblock %}
{% block mainblock %}

<body> 
    <!--loading -->
    <div class="loading">
        <div class="circle"></div>
    </div>
    <!--/-->

    <!-- Navigation-->
    {% include "header.html" %}
    <!--/-->
    
    <!--category-->
    <section class="categorie-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8">
                    <div class="categorie-title"> 
                         <small>
                            <a href="/">Home</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--blog-grid-->
        <section class="blog-grid">
            <div class="container-fluid">
                <div class="row">
                    {% comment %} <div class="col-lg-8 mt-30">
                        <div class="row">
                            <div class="col-lg-12">
                                <!--Post-1-->
                                <div class="post-card">
                                    <div class="post-card-image">
                                        <img src="{{ single_blog.blog_thumbnail.url }}" alt="">
                                    </div>
                                    <div class="post-card-content">
                                        <a href="{{ single_blog.category.get_absolute_url }}" class="categorie">{{ single_blog.category }}</a>
                                        <h5>{{ single_blog.title }}</h5>
                                        <p>{{ single_blog.discription | safe }}</p>
                                        <div class="post-card-info">
                                            <ul class="list-inline">
                                                <li>
                                                    <a href="#">{{ single_blog.author }}</a>
                                                </li>
                                                <li class="dot"></li>
                                                <li>{{ single_blog.creation | timesince }}</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!--/-->
                            


                                <!-- comment -->
                                <div class="pt-2 mb-11">
                                    <div class="mb-4">
                                        <h3>{{ comments.count }} Comment{{ comments.count | pluralize }}</h3>
                                    </div>
                                    <ul class="list-unstyled">
                                        <!-- Comment -->
                                        <li class="mb-5">
                                            {% for comment in comments %}
                                                <div class="media align-items-center mb-2">
                                                    <div class="media-body">
                                                        <div class="d-flex justify-content-between align-items-center">
                                                            <span class="mb-0">comments {{ forloop.counter }} by {{ comment.name }}</span>
                                                            <small class="text-muted">on {{ comment.publish }}</small>
                                                        </div>
                                                    </div>
                                                </div>

                                                <p class="h5">
                                                {{ comment.body | linebreaks }}
                                                </p>
                                                {% empty %}
                                                <p class="h5">
                                                there is no comments for this post
                                                </p>

                                            {% endfor %}
                                            <p class="h5">
                                                Make your comment
                                            </p>
                                            
                                        </li>
                                    </ul>


                                    <!-- Form -->
                                        <form action='.' method='POST' class="js-validate">
                                            <div class="form-row">
                                                <div class="col-sm-6 mb-sm-3">
                                                    <div class="js-form-message form-group">

                                                        <label class="input-label">Name</label>
                                                        <input
                                                        type="text"
                                                        class="form-control"
                                                        name="name"
                                                        id="inputName"
                                                        placeholder="Name"
                                                        aria-label="Name"
                                                        required
                                                        data-msg="Please enter your name."/>
                                                    </div>
                                                </div>
                                                <div class="col-12 mb-sm-3">
                                                    <div class="js-form-message form-group">
                                                    <label class="input-label">Comment</label>
                                                    <textarea
                                                        class="form-control"
                                                        name="body"
                                                        rows="7"
                                                        id="descriptionTextarea"
                                                        placeholder="Comment"
                                                        required
                                                        data-msg="Please enter your message."
                                                    ></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            {% csrf_token %}

                                            <div class="d-flex justify-align-content-lg-start">
                                                <button
                                                    type="submit"
                                                    class="btn btn-primary btn-wide transition-3d-hover">
                                                    Submit
                                                </button>
                                            </div>
                                        </form>
                                    <!-- End Form -->
                                </div>
                            </div>
                            <br>
                            <!--pagination-->
                            <div class="col-lg-12">
                                <div class="pagination mb--40">
                                    <ul class="list-inline">
                                        <li class="active">
                                            <a href="#">1</a>
                                        </li>
                                        <li>
                                            <a href="#">2</a>
                                        </li>
                                        <li>
                                            <a href="#">3</a>
                                        </li>
                                        <li>
                                            <a href="#">4</a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="arrow_carrot-2right"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            <!--/-->
                            </div> 
                        </div>
                    </div> {% endcomment %}
                    <div class="col-lg-12 max-width">
                        <!--widget-categories-->
                        <div class="widget">
                            <div class="section-title">
                                <h5>Categories</h5>
                            </div>
                            <ul class="widget-categories">
                            
                                {% for category in categories %}
                                    <li>
                                        <a href="{{ category.get_absolute_url }}" class="categorie">{{ category.name }}</a>
                                        <!--widget-categories <span class="ml-auto">10 Posts</span> -->
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!--widget-latest-posts-->
                        <div class="widget ">
                            <div class="section-title">
                                <h5>Latest Posts</h5>
                            </div>
                            <ul class="widget-latest-posts">
                            
                                {% for blog in blogs %}
                                    <li class="last-post">
                                        <div class="image">
                                            <a href="{{ blog.get_absolute_url }}">
                                                <img src="{{ blog.blog_thumbnail.url }}" alt="...">
                                            </a>
                                        </div>
                                        <div class="nb">2</div>
                                        <div class="content">
                                            <p>
                                                <a href="{{ blog.get_absolute_url }}">{{ blog.title}}</a>
                                            </p>
                                            <small>
                                                <span class="icon_clock_alt"></span>{{ blog.creation }}</small>
                                        </div>
                                    </li>
                                {% endfor %}
                                
                            </ul>
                        </div>
                        <!--/-->
                        
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!--/-->

    
    <!--footer-->
    {% include "footer.html" %}

    <!--Search-form-->
    <div class="search">
        <div class="container-fluid">
            <div class="search-width  text-center">
                <button type="button" class="close">
                    <i class="icon_close"></i>
                </button>
                <form class="search-form" action="#">
                    <input type="search" value="" placeholder="What are you looking for?">
                    <button type="submit" class="search-btn">search</button>
                </form>
            </div>
        </div>
    </div>
    <!--/-->

  {% endblock mainblock %}

templates/blog_temp/category.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
      categorie
{% endblock titleblock %}
{% block mainblock %}
    <!--masonry-layout-->
    <section class="section masonry-layout pt-45">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card-columns">
                        <!--Post-1-->
                        
                        {% for blog in blogs %}
                        <div class="card">
                            <div class="post-card">
                                <div class="post-card-image">
                                    <a href="{{ blog.get_absolute_url }}">
                                        <img src="{{ blog.blog_thumbnail.url }}" alt="image">
                                    </a>
        
                                </div>
                                <div class="post-card-content">
                                    <a href="{{ category.get_absolute_url }}" class="categorie"> {{ blog.category }}</a>
                                    <h5>
                                        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
                                    </h5>
                                    <p>{{ blog.short_discription }}</p>
                                    <div class="post-card-info">
                                        <ul class="list-inline">
                                            {% comment %} <li>
                                                <a href="author.html">
                                                    <img src="{% static 'blog/assets/img/author/1.jpg'%}" alt="">
                                                </a>
                                            </li> {% endcomment %}
                                            <li>
                                                <a href="#">{{ blog.author }}</a>
                                            </li>
                                            <li class="dot"></li>
                                            <li>{{ blog.creation }}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!--/-->

                    </div>
                    <!--pagination-->
                    <!--pagination-->


                    <div class="pagination justify-content-center">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">« first</a>
                                <a href="?page={{ page_obj.previous_page_number }}"><b>Previous</b></a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}"><b>Next</b></a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last »</a>
                            {% endif %}
                        </span>
                    </div>

                        <!-- pagination -->
                </div>
            </div>
        </div>
    </section>
    <!--/-->

    <!--footer-->
    {% include "footer.html" %}
    <!--Search-form-->
    <div class="search">
        <div class="container-fluid">
            <div class="search-width  text-center">
                <button type="button" class="close">
                    <i class="icon_close"></i>
                </button>
                <form class="search-form" action="#">
                    <input type="search" value="" placeholder="What are you looking for?">
                    <button type="submit" class="search-btn">search</button>
                </form>
            </div>
        </div>
    </div>
    <!--/-->
    {% endblock mainblock %}


templates/blog_temp/home_page.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
      Blog Homepage
{% endblock titleblock %}
{% block mainblock %}

<!-- Hero Section -->
      {% comment %} <div class="container space-2">
        <div class="row justify-content-lg-between align-items-lg-center">
            <div class="col-sm-10 col-lg-5 mb-7 mb-lg-0">
                <img
                class="img-fluid"
                src="assets/img/nature.jpg"
                alt="Image Des"
                />
            </div>

            <div class="col-lg-6">
                <div class="mb-5">
                    <h1 class="display-4 mb-3">
                        Unlock your span
                        <br />
                        <span class="text-primary font-weight-bold">
                        <span class="js-text-animation"></span>
                        </span>
                    </h1>
                    <p class="lead">
                        With our platform, you can quantify your skills, grow in your
                        role and stay relevant on critical topics.
                    </p>
                </div>

            <div class="d-sm-flex align-items-sm-center flex-sm-wrap">
              <a class="btn btn-primary mb-2" href="#"
                >Start a Free Trial</a
              >

              <div class="mx-2"></div>

              <!-- Fancybox -->
              <a
                class="js-fancybox video-player video-player-btn media align-items-center text-dark mb-2"
                href="javascript:;"
                data-hs-fancybox-options='{
                 "src": "//youtube.com/0qisGSwZym4",
                 "caption": "Blueberry - Responsive Website Template",
                 "speed": 700,
                 "buttons": ["fullScreen", "close"],
                 "youtube": {
                   "autoplay": 1
                 }
               }'
              >
                <span class="video-player-icon shadow-soft mr-3">
                  <i class="fa fa-play"></i>
                </span>
                <span class="media-body"> How it works </span>
              </a>
              <!-- End Fancybox -->
            </div>
          </div>
        </div>
      </div> {% endcomment %}
    <br>
    <br>
    <div class="col-md-60 col-md-offset-1 intro-header" style="background-image: url('blog/assets/img/nature.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Modern Blog</h1>
                        <span class="subheading">e-pulse Blog Powered by KonnectCode</span>
                    </div>
                </div>
            </div>
        </div>
    </div>  



    <!--masonry-layout-->
    <section class="section masonry-layout pt-45">
    <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card-columns">
                        <!--Post-1-->
                        
                        {% for blog in all_page_obj %}
                        <div class="card">
                            <div class="post-card">
                                <div class="post-card-image">
                                    <a href="{{ blog.get_absolute_url }}">
                                        <img src="{{ blog.blog_thumbnail.url }}" alt="image">
                                    </a>
        
                                </div>
                                <div class="post-card-content">
                                    <a href="{{ blog.category.get_absolute_url }}" class="categorie">{{ blog.category }}</a>
                                    <h5>
                                        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
                                    </h5>
                                    <p>{{ blog.short_discription }}</p>
                                    <div class="post-card-info">
                                        <ul class="list-inline">
                                            {% comment %} <li>
                                                <a href="author.html">
                                                    <img src="{% static 'blog/assets/img/author/1.jpg'%}" alt="">
                                                </a>
                                            </li> {% endcomment %}
                                            <li>
                                                <a href="#">{{ blog.author }}</a>
                                            </li>
                                            <li class="dot"></li>
                                            <li>{{ blog.creation | timesince }}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!--/-->

                    </div>
                    <!--pagination-->


                    <div class="pagination justify-content-center">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">« first</a>
                                <a href="?page={{ page_obj.previous_page_number }}"><b>Previous</b></a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}"><b>Next</b></a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last »</a>
                            {% endif %}
                        </span>
                    </div>

                        <!-- pagination -->
                </div>
            </div>
        </div>
    </section>
    <!--/-->

    <!--footer-->
    {% include "footer.html" %}
    <!--Search-form-->
    <div class="search">
        <div class="container-fluid">
            <div class="search-width  text-center">
                <button type="button" class="close">
                    <i class="icon_close"></i>
                </button>
                <form method="GET" class="search-form" action="{% url 'Blog_app:search_blog' %}">
                    <input type="search" value="" name="q" placeholder="What are you looking for?">
                    <button type="submit" class="search-btn">search</button>
                </form>
            </div>
        </div>
    </div>
    <!--/-->
    {% endblock mainblock %}


templates/blog_temp/index.html
{% extends 'base.html' %}
{% load static %}
{% block titleblock %}
      Rakib's Personal Blog
{% endblock titleblock %}
{% block mainblock %}
    <!--masonry-layout-->
    <section class="section masonry-layout pt-45">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card-columns">
                        <!--Post-1-->
                        
                        {% for blog in page_obj %}
                        <div class="card">
                            <div class="post-card">
                                <div class="post-card-image">
                                    <a href="{{ blog.get_absolute_url }}">
                                        <img src="{{ blog.blog_thumbnail.url }}" alt="image">
                                    </a>
        
                                </div>
                                <div class="post-card-content">
                                    <a href="{{ blog.category.get_absolute_url }}" class="categorie">{{ blog.category }}</a>
                                    <h5>
                                        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a>
                                    </h5>
                                    <p>{{ blog.short_discription }}</p>
                                    <div class="post-card-info">
                                        <ul class="list-inline">
                                            {% comment %} <li>
                                                <a href="author.html">
                                                    <img src="{% static 'blog/assets/img/author/1.jpg'%}" alt="">
                                                </a>
                                            </li> {% endcomment %}
                                            <li>
                                                <a href="#">{{ blog.author }}</a>
                                            </li>
                                            <li class="dot"></li>
                                            <li>{{ blog.creation | timesince }}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!--/-->

                    </div>
                    <!--pagination-->


                    <div class="pagination justify-content-center">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">« first</a>
                                <a href="?page={{ page_obj.previous_page_number }}"><b>Previous</b></a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}"><b>Next</b></a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">last »</a>
                            {% endif %}
                        </span>
                    </div>

                        <!-- pagination -->
                </div>
            </div>
        </div>
    </section>
    <!--/-->

    <!--footer-->
    {% include "footer.html" %}
    <!--Search-form-->
    <div class="search">
        <div class="container-fluid">
            <div class="search-width  text-center">
                <button type="button" class="close">
                    <i class="icon_close"></i>
                </button>
                <form method="GET" class="search-form" action="{% url 'Blog_app:search_blog' %}">
                    <input type="search" value="" name="q" placeholder="What are you looking for?">
                    <button type="submit" class="search-btn">search</button>
                </form>
            </div>
        </div>
    </div>
    <!--/-->
    {% endblock mainblock %}
